"""Transplant-case state machine. Clinical authorization remains with humans."""
STATES = ("CREATED","MEDICAL_REVIEW","MATCH_SEARCH","CANDIDATE_FOUND","DOCTOR_REVIEW","HOSPITAL_COORDINATION","APPROVED_FOR_PROCEDURE","PROCEDURE_SCHEDULED","COMPLETED","CANCELLED","ON_HOLD","REJECTED")
TRANSITIONS = {
 "CREATED":{"MEDICAL_REVIEW","CANCELLED","ON_HOLD"},
 "MEDICAL_REVIEW":{"MATCH_SEARCH","ON_HOLD","REJECTED","CANCELLED"},
 "MATCH_SEARCH":{"CANDIDATE_FOUND","ON_HOLD","CANCELLED"},
 "CANDIDATE_FOUND":{"DOCTOR_REVIEW","ON_HOLD","CANCELLED"},
 "DOCTOR_REVIEW":{"HOSPITAL_COORDINATION","REJECTED","ON_HOLD","CANCELLED"},
 "HOSPITAL_COORDINATION":{"APPROVED_FOR_PROCEDURE","REJECTED","ON_HOLD","CANCELLED"},
 "APPROVED_FOR_PROCEDURE":{"PROCEDURE_SCHEDULED","ON_HOLD","CANCELLED"},
 "PROCEDURE_SCHEDULED":{"COMPLETED","ON_HOLD","CANCELLED"},
 "ON_HOLD":{"MEDICAL_REVIEW","MATCH_SEARCH","DOCTOR_REVIEW","HOSPITAL_COORDINATION","CANCELLED"},
 "REJECTED":set(), "CANCELLED":set(), "COMPLETED":set()
}
def validate_transition(current,new):
 current=current.upper(); new=new.upper()
 if current not in STATES or new not in TRANSITIONS[current]: raise ValueError(f"Invalid case transition: {current} -> {new}")
 return new
